import request from 'supertest';
import mongoose from 'mongoose';
import app from '../../../app.js';
import seedUsers from '../../helpers/seedUsers.js';
import { getCustomerToken, getSellerToken, getAdminToken } from '../../helpers/getTokens.js';
import Wishlist from '../../../modules/wishlist/wishlist.model.js';
import Product from '../../../modules/product/product.model.js';
import User from '../../../modules/user/user.model.js';

let customerToken, sellerToken, adminToken;
let activeProduct, heldProduct;

beforeAll(async () => {
  await seedUsers();
  customerToken = await getCustomerToken();
  sellerToken   = await getSellerToken();
  adminToken    = await getAdminToken();

  // category via HTTP so slug is auto-generated by the service
  const categoryRes = await request(app)
    .post('/admin/categories')
    .set('Authorization', `Bearer ${adminToken}`)
    .send({ name: 'Wishlist Test Category', image: 'https://example.com/cat.jpg' });

  const categoryId = categoryRes.body.data._id;

  // template via HTTP
  await request(app)
    .put(`/admin/categories/${categoryId}/template`)
    .set('Authorization', `Bearer ${adminToken}`)
    .send({ sizeOptions: ['S', 'M', 'L'], specFields: [] });

  const sellerId = new mongoose.Types.ObjectId();

  const baseVariant = {
    colorName: 'Black',
    colorCode: '#000000',
    baseColor: 'Black',
    size: 'M',
    price: 1000,
    discount: 10,
    stock: 20,
  };

  activeProduct = await Product.create({
    sellerId,
    categoryId,
    name: 'Active Product',
    slug: 'active-product-' + sellerId.toString().slice(-5),
    brand: 'TestBrand',
    gender: 'Unisex',
    description: 'An active product',
    images: ['https://example.com/img1.jpg'],
    variants: [baseVariant],
    specifications: [],
    status: 'active',
    colorNames: ['Black'],
    baseColors: ['Black'],
  });

  heldProduct = await Product.create({
    sellerId,
    categoryId,
    name: 'Held Product',
    slug: 'held-product-' + sellerId.toString().slice(-5),
    brand: 'TestBrand',
    gender: 'Unisex',
    description: 'A held product',
    images: ['https://example.com/img2.jpg'],
    variants: [baseVariant],
    specifications: [],
    status: 'held',
    colorNames: ['Black'],
    baseColors: ['Black'],
  });
});

// ─── Request Helpers ─────────────────────────────────────────────────────────

const addToWishlist = (token, data) =>
  request(app)
    .post('/wishlist')
    .set('Authorization', `Bearer ${token}`)
    .send(data);

const getWishlist = (token) =>
  request(app)
    .get('/wishlist')
    .set('Authorization', `Bearer ${token}`);

const removeFromWishlist = (token, productId) =>
  request(app)
    .delete(`/wishlist/${productId}`)
    .set('Authorization', `Bearer ${token}`);

// ─── Valid Data Factory ──────────────────────────────────────────────────────

const validAddData = (overrides = {}) => ({
  productId: activeProduct._id.toString(),
  ...overrides,
});

// ─── POST /wishlist ──────────────────────────────────────────────────────────

describe('POST /wishlist', () => {
  afterEach(async () => {
    await Wishlist.deleteMany({});
  });

  it('should add an active product to wishlist', async () => {
    const res = await addToWishlist(customerToken, validAddData());
    expect(res.status).toBe(200);
    expect(res.body.success).toBe(true);
    expect(res.body.data.wishlist.products).toHaveLength(1);
  });

  it('should return 400 if product already in wishlist', async () => {
    await addToWishlist(customerToken, validAddData());
    const res = await addToWishlist(customerToken, validAddData());
    expect(res.status).toBe(400);
    expect(res.body.errorCode).toBe('VALIDATION_ERROR');
  });

  it('should return 404 for a held product', async () => {
    const res = await addToWishlist(customerToken, validAddData({ productId: heldProduct._id.toString() }));
    expect(res.status).toBe(404);
    expect(res.body.errorCode).toBe('NOT_FOUND');
  });

  it('should return 404 for a non-existent productId', async () => {
    const res = await addToWishlist(customerToken, validAddData({ productId: new mongoose.Types.ObjectId().toString() }));
    expect(res.status).toBe(404);
    expect(res.body.errorCode).toBe('NOT_FOUND');
  });

  it('should return 400 for invalid productId format', async () => {
    const res = await addToWishlist(customerToken, validAddData({ productId: 'not-an-objectid' }));
    expect(res.status).toBe(400);
    expect(res.body.errorCode).toBe('VALIDATION_ERROR');
  });

  it('should return 400 if productId is missing', async () => {
    const res = await addToWishlist(customerToken, {});
    expect(res.status).toBe(400);
    expect(res.body.errorCode).toBe('VALIDATION_ERROR');
  });

  it('should return 401 with no token', async () => {
    const res = await request(app).post('/wishlist').send(validAddData());
    expect(res.status).toBe(401);
  });

  it('should return 403 for seller', async () => {
    const res = await addToWishlist(sellerToken, validAddData());
    expect(res.status).toBe(403);
  });

  it('should return 403 for admin', async () => {
    const res = await addToWishlist(adminToken, validAddData());
    expect(res.status).toBe(403);
  });
});

// ─── GET /wishlist ───────────────────────────────────────────────────────────

describe('GET /wishlist', () => {
  afterEach(async () => {
    await Wishlist.deleteMany({});
  });

  it('should return empty array if no wishlist exists', async () => {
    const res = await getWishlist(customerToken);
    expect(res.status).toBe(200);
    expect(res.body.data.products).toEqual([]);
  });

  it('should return wishlist items with correct shape for active product', async () => {
    await addToWishlist(customerToken, validAddData());
    const res = await getWishlist(customerToken);
    expect(res.status).toBe(200);
    const item = res.body.data.products[0];
    expect(item.available).toBe(true);
    expect(item.name).toBe('Active Product');
    expect(item.image).toBeDefined();
    expect(item.priceRange).toHaveProperty('min');
    expect(item.priceRange).toHaveProperty('max');
  });

  it('should mark held product as available: false in wishlist response', async () => {
    const customer = await User.findOne({ role: 'customer' });
    await Wishlist.create({ userId: customer._id, products: [heldProduct._id] });

    const res = await getWishlist(customerToken);
    expect(res.status).toBe(200);
    const item = res.body.data.products[0];
    expect(item.available).toBe(false);
    expect(item.name).toBe('Held Product');
  });

  it('should return available: false for a product deleted from DB after wishlisting', async () => {
    const customer = await User.findOne({ role: 'customer' });
    const ghostId = new mongoose.Types.ObjectId();
    await Wishlist.create({ userId: customer._id, products: [ghostId] });

    const res = await getWishlist(customerToken);
    expect(res.status).toBe(200);
    const item = res.body.data.products[0];
    expect(item.available).toBe(false);
    expect(item.name).toBeNull();
  });

  it('should return 401 with no token', async () => {
    const res = await request(app).get('/wishlist');
    expect(res.status).toBe(401);
  });

  it('should return 403 for seller', async () => {
    const res = await getWishlist(sellerToken);
    expect(res.status).toBe(403);
  });

  it('should return 403 for admin', async () => {
    const res = await getWishlist(adminToken);
    expect(res.status).toBe(403);
  });
});

// ─── DELETE /wishlist/:productId ─────────────────────────────────────────────

describe('DELETE /wishlist/:productId', () => {
  afterEach(async () => {
    await Wishlist.deleteMany({});
  });

  it('should remove a product from wishlist', async () => {
    await addToWishlist(customerToken, validAddData());
    const res = await removeFromWishlist(customerToken, activeProduct._id);
    expect(res.status).toBe(200);
    expect(res.body.data.wishlist.products).toHaveLength(0);
  });

  it('should return 404 if product not in wishlist', async () => {
    const res = await removeFromWishlist(customerToken, activeProduct._id);
    expect(res.status).toBe(404);
    expect(res.body.errorCode).toBe('NOT_FOUND');
  });

  it('should return 401 with no token', async () => {
    const res = await request(app).delete(`/wishlist/${activeProduct._id}`);
    expect(res.status).toBe(401);
  });

  it('should return 403 for seller', async () => {
    const res = await removeFromWishlist(sellerToken, activeProduct._id);
    expect(res.status).toBe(403);
  });

  it('should return 403 for admin', async () => {
    const res = await removeFromWishlist(adminToken, activeProduct._id);
    expect(res.status).toBe(403);
  });
});