export const ROLES = {
  CUSTOMER: 'customer',
  SELLER: 'seller',
  ADMIN: 'admin',
}

export const USER_STATUS = {
  ACTIVE: 'active',
  PENDING: 'pending',
  BLOCKED: 'blocked',
  DELETED: 'deleted',
  REJECTED: 'rejected',
}

export const ORDER_STATUS = {
  PLACED: 'placed',
  ACCEPTED: 'accepted',
  PACKED: 'packed',
  SHIPPED: 'shipped',
  OUT_FOR_DELIVERY: 'out_for_delivery',
  DELIVERED: 'delivered',
  CANCELLED: 'cancelled',
  REJECTED: 'rejected',
}

export const NOTIFICATION_TYPES = {
  ORDER_PLACED: 'ORDER_PLACED',
  ORDER_ACCEPTED: 'ORDER_ACCEPTED',
  ORDER_PACKED: 'ORDER_PACKED',
  ORDER_SHIPPED: 'ORDER_SHIPPED',
  ORDER_OUT_FOR_DELIVERY: 'ORDER_OUT_FOR_DELIVERY',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_REJECTED: 'ORDER_REJECTED',
  RETURN_REQUESTED: 'RETURN_REQUESTED',
  RETURN_UPDATED: 'RETURN_UPDATED',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  WALLET_CREDITED: 'WALLET_CREDITED',
  WITHDRAWAL_PROCESSED: 'WITHDRAWAL_PROCESSED',
  WITHDRAWAL_REJECTED: 'WITHDRAWAL_REJECTED',
  SELLER_APPROVED: 'SELLER_APPROVED',
  SELLER_REJECTED: 'SELLER_REJECTED',
  PRODUCT_HELD: 'PRODUCT_HELD',
  REVIEW_RECEIVED: 'REVIEW_RECEIVED',
  SELLER_RESPONSE_RECEIVED: 'SELLER_RESPONSE_RECEIVED',
}

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 12,
  MAX_LIMIT: 50,
}

export const APP_META = {
  NAME: 'Wear Web',
  TAGLINE: 'Built for modern apparel commerce',
}